# Generated by Django 5.1.1 on 2024-09-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_meetings_rating'),
        ('coach', '0003_employee_adress_employee_password_and_more'),
        ('customer', '0007_rename_payments_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetings',
            new_name='Meeting',
        ),
    ]
