# Generated by Django 5.1.1 on 2024-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('tip', models.CharField(max_length=5000)),
            ],
        ),
    ]
