# Generated by Django 5.1.1 on 2024-09-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_employee_image'),
        ('customer', '0002_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.employee'),
        ),
    ]
