# Generated by Django 5.1.1 on 2024-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_coach_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('CC', 'Credit Card')], max_length=10),
        ),
    ]
