# Generated by Django 5.1.1 on 2024-09-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_birth_day_alter_customer_coach_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
