# Generated by Django 5.1.1 on 2024-09-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_birth_day_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='types',
            new_name='type',
        ),
    ]
