# Generated by Django 5.1.1 on 2024-09-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_types_clothes_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Clothe',
        ),
    ]
