# Generated by Django 5.1.1 on 2024-09-04 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='employees_image/'),
            preserve_default=False,
        ),
    ]
