# Generated by Django 5.1.1 on 2024-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
