# Generated by Django 5.1.1 on 2024-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
