# Generated by Django 5.1.1 on 2024-09-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_employee_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
