# Generated by Django 5.1.1 on 2024-09-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_alter_employee_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
