# Generated by Django 5.1.1 on 2024-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_alter_employee_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_day',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
