# Generated by Django 5.1.1 on 2024-09-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_remove_employee_birth_day_employee_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adress',
            new_name='address',
        ),
    ]
