# Generated by Django 5.1.1 on 2024-09-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_rename_adress_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
