# Generated by Django 5.1.1 on 2024-09-10 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=5000)),
                ('duration', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('location_x', models.CharField(max_length=500)),
                ('location_y', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('location_name', models.CharField(max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
